# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chess_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from pathlib import Path

# Add parent directory to Python path
sys.path.insert(0, str(Path(__file__).parent.parent))
from mod_button import ModButton
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QMainWindow):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1114, 848)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 60, 800, 800))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.add_buttons()

    def add_buttons(self):
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.buttons={}
        btn=self.buttons
        cnt=0
        for x in range(8):
            cnt+=1
            for y in range(8):
                btn[(x,y)]=ModButton()
                btn[(x,y)].add_x_y(x,y)
                self.gridLayout.addWidget(btn[(x,y)],x,y)
                btn[(x,y)].setFixedSize(QtCore.QSize(100,100))
                # btn[(x,y)].setStyleSheet("border:none;")
                style1,style2="background-color:green","background-color:red"
                
                if (y+cnt)%2==0:
                    btn[(x,y)].setStyleSheet(style1)
                else:
                    btn[(x,y)].setStyleSheet(style2)
                

                    
                
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

app=QtWidgets.QApplication([])
w=Ui_Dialog()
w.setupUi(w)
w.show()

import sys

sys.exit(app.exec_())